# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-21 11:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0001_initial'),
        ('things', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='technologyorder',
            name='payee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technology_payee', to=settings.AUTH_USER_MODEL, verbose_name='\u6536\u6b3e\u4eba'),
        ),
        migrations.AddField(
            model_name='technologyorder',
            name='payer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technology_payer', to=settings.AUTH_USER_MODEL, verbose_name='\u652f\u4ed8\u8005'),
        ),
        migrations.AddField(
            model_name='technologyorder',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='things.Technology', verbose_name='\u4ea7\u54c1'),
        ),
        migrations.AddField(
            model_name='softwareorder',
            name='payee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='software_payee', to=settings.AUTH_USER_MODEL, verbose_name='\u6536\u6b3e\u4eba'),
        ),
        migrations.AddField(
            model_name='softwareorder',
            name='payer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='software_payer', to=settings.AUTH_USER_MODEL, verbose_name='\u652f\u4ed8\u8005'),
        ),
        migrations.AddField(
            model_name='softwareorder',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='things.Software', verbose_name='\u4ea7\u54c1'),
        ),
        migrations.AddField(
            model_name='equipmentorder',
            name='payee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_payee', to=settings.AUTH_USER_MODEL, verbose_name='\u6536\u6b3e\u4eba'),
        ),
        migrations.AddField(
            model_name='equipmentorder',
            name='payer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_payer', to=settings.AUTH_USER_MODEL, verbose_name='\u652f\u4ed8\u8005'),
        ),
        migrations.AddField(
            model_name='equipmentorder',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='things.Equipment', verbose_name='\u4ea7\u54c1'),
        ),
    ]
