# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-28 17:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('thing_types', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('equip_id', models.AutoField(primary_key=True, serialize=False, verbose_name='\u8bbe\u5907ID')),
                ('equip_name', models.CharField(max_length=100, verbose_name='\u8bbe\u5907\u540d\u79f0')),
                ('produce_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u751f\u4ea7\u65e5\u671f')),
                ('equip_over', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u5230\u671f\u5e74\u9650')),
                ('equip_expense', models.FloatField(default=0.0, verbose_name='\u8bbe\u5907\u4ef7\u683c')),
                ('equip_start', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u51fa\u79df\u5f00\u59cb\u65f6\u95f4')),
                ('equip_end', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u51fa\u79df\u7ed3\u675f\u65f6\u95f4')),
                ('equip_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='\u51fa\u79df\u8d39\u7528(\u5143/\u5929)')),
                ('equip_picture', models.ImageField(default='image/image_equipment/default.png', upload_to='image/image_equipment/%Y/%m', verbose_name='\u8bbe\u5907\u56fe\u7247')),
                ('equip_parameter', models.TextField(verbose_name='\u6027\u80fd\u53c2\u6570')),
                ('equip_place', models.CharField(max_length=50, verbose_name='\u5730\u70b9')),
                ('equip_comment', models.CharField(blank=True, max_length=300, null=True, verbose_name='\u5907\u6ce8')),
                ('equip_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User', verbose_name='\u8bbe\u5907\u6240\u5c5e')),
                ('equip_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thing_types.EquipmentType', verbose_name='\u8bbe\u5907\u7c7b\u522b')),
            ],
            options={
                'verbose_name': '\u8bbe\u5907',
                'verbose_name_plural': '\u8bbe\u5907',
            },
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('software_id', models.AutoField(primary_key=True, serialize=False, verbose_name='\u8bbe\u5907ID')),
                ('software_name', models.CharField(max_length=100, verbose_name='\u8f6f\u4ef6\u540d\u79f0')),
                ('software_expense', models.FloatField(default=0.0, verbose_name='\u8f6f\u4ef6\u4ef7\u683c')),
                ('software_start', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u51fa\u79df\u5f00\u59cb\u65f6\u95f4')),
                ('software_end', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u51fa\u79df\u7ed3\u675f\u65f6\u95f4')),
                ('software_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='\u51fa\u79df\u8d39\u7528(\u5143/\u5929)')),
                ('software_image', models.ImageField(default='image/image_software/default.png', upload_to='image/image_software/%Y/%m', verbose_name='\u8f6f\u4ef6\u56fe\u7247')),
                ('software_describe', models.TextField(verbose_name='\u8f6f\u4ef6\u63cf\u8ff0')),
                ('os', models.CharField(max_length=100, verbose_name='\u8fd0\u884c\u5e73\u53f0')),
                ('software_comment', models.CharField(blank=True, max_length=300, null=True, verbose_name='\u5907\u6ce8')),
                ('software_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User', verbose_name='\u8f6f\u4ef6\u6240\u5c5e')),
                ('software_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thing_types.SoftwareType', verbose_name='\u8f6f\u4ef6\u7c7b\u522b')),
            ],
            options={
                'verbose_name': '\u8f6f\u4ef6',
                'verbose_name_plural': '\u8f6f\u4ef6',
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('tech_id', models.AutoField(primary_key=True, serialize=False, verbose_name='\u6280\u672fID')),
                ('tech_name', models.CharField(max_length=100, verbose_name='\u6280\u672f\u540d\u79f0')),
                ('tech_info', models.CharField(max_length=300, verbose_name='\u6280\u672f\u670d\u52a1\u4fe1\u606f')),
                ('tech_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='\u6280\u672f\u4ef7\u683c(\u5143/\u5929)')),
                ('tech_image', models.ImageField(default='image/image_technology/default.png', upload_to='image/image_technology/%Y/%m', verbose_name='\u6280\u672f\u56fe\u7247')),
                ('tech_commet', models.CharField(blank=True, max_length=300, null=True, verbose_name='\u5907\u6ce8')),
                ('tech_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User', verbose_name='\u6280\u672f\u6240\u5c5e')),
                ('tech_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thing_types.TechnologyType', verbose_name='\u6280\u672f\u7c7b\u522b')),
            ],
            options={
                'verbose_name': '\u6280\u672f',
                'verbose_name_plural': '\u6280\u672f',
            },
        ),
    ]
