# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-21 11:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('things', '0001_initial'),
        ('thing_types', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='tech_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u6280\u672f\u6240\u5c5e'),
        ),
        migrations.AddField(
            model_name='technology',
            name='tech_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thing_types.TechnologyType', verbose_name='\u6280\u672f\u7c7b\u522b'),
        ),
        migrations.AddField(
            model_name='software',
            name='software_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u8f6f\u4ef6\u6240\u5c5e'),
        ),
        migrations.AddField(
            model_name='software',
            name='software_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thing_types.SoftwareType', verbose_name='\u8f6f\u4ef6\u7c7b\u522b'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='equip_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u8bbe\u5907\u6240\u5c5e'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='equip_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thing_types.EquipmentType', verbose_name='\u8bbe\u5907\u7c7b\u522b'),
        ),
    ]
