# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-21 11:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(default='', max_length=100, verbose_name='\u7c7b\u522b\u540d')),
                ('type_grade', models.IntegerField(choices=[(1, '\u4e00\u7ea7\u7c7b\u76ee'), (2, '\u4e8c\u7ea7\u7c7b\u76ee')], verbose_name='\u7c7b\u76ee\u7ea7\u522b')),
                ('is_tab', models.BooleanField(default=False, verbose_name='\u662f\u5426\u5bfc\u822a')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('parent_grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_equip', to='thing_types.EquipmentType', verbose_name='\u7236\u7c7b\u76ee\u7ea7\u522b')),
            ],
            options={
                'verbose_name': '\u8bbe\u5907\u5206\u7c7b',
                'verbose_name_plural': '\u8bbe\u5907\u5206\u7c7b',
            },
        ),
        migrations.CreateModel(
            name='SoftwareType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(default='', max_length=100, verbose_name='\u7c7b\u522b\u540d')),
                ('type_grade', models.IntegerField(choices=[(1, '\u4e00\u7ea7\u7c7b\u76ee'), (2, '\u4e8c\u7ea7\u7c7b\u76ee')], verbose_name='\u7c7b\u76ee\u7ea7\u522b')),
                ('is_tab', models.BooleanField(default=False, verbose_name='\u662f\u5426\u5bfc\u822a')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('parent_grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_soft', to='thing_types.SoftwareType', verbose_name='\u7236\u7c7b\u76ee\u7ea7\u522b')),
            ],
            options={
                'verbose_name': '\u8f6f\u4ef6\u5206\u7c7b',
                'verbose_name_plural': '\u8f6f\u4ef6\u5206\u7c7b',
            },
        ),
        migrations.CreateModel(
            name='TechnologyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(default='', max_length=100, verbose_name='\u7c7b\u522b\u540d')),
                ('type_grade', models.IntegerField(choices=[(1, '\u4e00\u7ea7\u7c7b\u76ee'), (2, '\u4e8c\u7ea7\u7c7b\u76ee')], verbose_name='\u7c7b\u76ee\u7ea7\u522b')),
                ('is_tab', models.BooleanField(default=False, verbose_name='\u662f\u5426\u5bfc\u822a')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('parent_grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_tech', to='thing_types.TechnologyType', verbose_name='\u7236\u7c7b\u76ee\u7ea7\u522b')),
            ],
            options={
                'verbose_name': '\u6280\u672f\u5206\u7c7b',
                'verbose_name_plural': '\u6280\u672f\u5206\u7c7b',
            },
        ),
    ]
