# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-21 11:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('demand_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='\u9700\u6c42ID')),
                ('type', models.CharField(choices=[('\u8f6f\u4ef6', '\u8f6f\u4ef6'), ('\u6280\u672f', '\u6280\u672f'), ('\u8bbe\u5907', '\u8bbe\u5907')], default=('\u8f6f\u4ef6', '\u8f6f\u4ef6'), max_length=50, verbose_name='\u5206\u7c7b')),
                ('title', models.CharField(default='', max_length=100, verbose_name='\u6807\u9898')),
                ('content', models.TextField(default='', max_length=1000, verbose_name='\u5185\u5bb9')),
                ('time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u65f6\u95f4\u6bb5')),
                ('money', models.CharField(default='', max_length=50, verbose_name='\u51fa\u79df\u8d39\u7528')),
            ],
            options={
                'verbose_name': '\u9700\u6c42\u53d1\u5e03',
                'verbose_name_plural': '\u9700\u6c42\u53d1\u5e03',
            },
        ),
        migrations.CreateModel(
            name='EquipmentCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u8bbe\u5907\u6536\u85cf',
                'verbose_name_plural': '\u8bbe\u5907\u6536\u85cf',
            },
        ),
        migrations.CreateModel(
            name='EquipmentIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u53d1\u5e03\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u8bbe\u5907\u53d1\u5e03',
                'verbose_name_plural': '\u8bbe\u5907\u53d1\u5e03',
            },
        ),
        migrations.CreateModel(
            name='SoftwareCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u8f6f\u4ef6\u6536\u85cf',
                'verbose_name_plural': '\u8f6f\u4ef6\u6536\u85cf',
            },
        ),
        migrations.CreateModel(
            name='SoftwareIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u53d1\u5e03\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u8f6f\u4ef6\u53d1\u5e03',
                'verbose_name_plural': '\u8f6f\u4ef6\u53d1\u5e03',
            },
        ),
        migrations.CreateModel(
            name='TechnologyCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u6280\u672f\u6536\u85cf',
                'verbose_name_plural': '\u6280\u672f\u6536\u85cf',
            },
        ),
        migrations.CreateModel(
            name='TechnologyIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u53d1\u5e03\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u6280\u672f\u53d1\u5e03',
                'verbose_name_plural': '\u6280\u672f\u53d1\u5e03',
            },
        ),
    ]
