# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-21 11:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operations', '0001_initial'),
        ('things', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='technologyissue',
            name='issuer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u53d1\u5e03\u8005'),
        ),
        migrations.AddField(
            model_name='technologyissue',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='things.Technology', verbose_name='\u6280\u672f\u4ea7\u54c1'),
        ),
        migrations.AddField(
            model_name='technologycollection',
            name='collector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u6536\u85cf\u8005'),
        ),
        migrations.AddField(
            model_name='technologycollection',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='things.Technology', verbose_name='\u6280\u672f\u4ea7\u54c1'),
        ),
        migrations.AddField(
            model_name='softwareissue',
            name='issuer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u53d1\u5e03\u8005'),
        ),
        migrations.AddField(
            model_name='softwareissue',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='things.Software', verbose_name='\u8f6f\u4ef6\u4ea7\u54c1'),
        ),
        migrations.AddField(
            model_name='softwarecollection',
            name='collector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u6536\u85cf\u8005'),
        ),
        migrations.AddField(
            model_name='softwarecollection',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='things.Software', verbose_name='\u8f6f\u4ef6\u4ea7\u54c1'),
        ),
        migrations.AddField(
            model_name='equipmentissue',
            name='issuer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u53d1\u5e03\u8005'),
        ),
        migrations.AddField(
            model_name='equipmentissue',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='things.Equipment', verbose_name='\u8bbe\u5907\u4ea7\u54c1'),
        ),
        migrations.AddField(
            model_name='equipmentcollection',
            name='collector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u6536\u85cf\u8005'),
        ),
        migrations.AddField(
            model_name='equipmentcollection',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='things.Equipment', verbose_name='\u8bbe\u5907\u4ea7\u54c1'),
        ),
        migrations.AddField(
            model_name='demand',
            name='demander',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237'),
        ),
    ]
